stages:
  - build
  - notify
  - test
build-frontend-code-job:
  stage: build  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
    - echo "${CI_JOB_ID}=build_job_id" >> build_id.env
  artifacts:
    reports:
    dotenv: build_id.env
    name: "$CI_JOB_NAME"   #
    paths:
    - frontend/dist/frontend
sonarqube-frontend-sast:
  stage: test
  image: 
    name: sonarsource/sonar-scanner-cli:latest
#   variables:
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - .sonar/cache
  script:
    - cd frontend
    - sonar-scanner -X -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${SONAR_PROJECT_KEY_F} -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONAR_LOGIN_F}
  needs:
  - build-frontend-code-job 
telegram-notification-frontend:
  variables:
    CI_JOB_NAME: build-frontend-code-job
    CHAT_ID: "-1002134018008"
    URL_TELEGRAM_BOT: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify
  only:
    changes:
    - frontend/*
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\": \"$CHAT_ID\", \"text\": \"Садовский Денис собрал frontend. Ссылка на артефакт: $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/download?job=$CI_JOB_NAME\"}" $URL_TELEGRAM_BOT '
##    - sh ci-notify.sh
  needs:
    - job: build-frontend-code-job
      ref: release-0.0.1
      artifacts: true

