stages:
  - build
  - notify
build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
    - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
telegram-notification-backend:
  variables:
#    CHAT-ID: "-1002134018008"
    URL: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify
  only:
    changes:
    - backend/*
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
#    - sh ci-notify.sh
    - curl -X POST -H 'Content-type: application/json' --data '{"chat_id": "-1002134018008"} $URL'
  needs:
    - build-backend-code-job
