stages:
  - build
  - notify
build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
    - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
telegram-notification-backend:
  variables:
    CHAT_ID: "-1002134018008"
    URL_TELEGRAM_BOT: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify
  only:
    changes:
    - backend/*
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
#    - 'curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\": \"-1002134018008\", \"text\": \"CI: test:\"}" https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage '
    - 'curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\": \"$CHAT_ID\", \"text\": \"Садовский Денис собрал backend. Ссылка на артефакт: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$CI_JOB_NAME\"}" $URL_TELEGRAM_BOT '
##    - sh ci-notify.sh
  needs:
    - build-backend-code-job
