stages:
  - build
  - notify
build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
	 telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
  script:
    - sh ci-notify.sh "back готовченко"
  needs:
    - build-backend-code-job
